/* Player API plugin (for pause vimeo video): https://github.com/vimeo/player-api/tree/master/javascript */
var Froogaloop=function(){function e(a){return new e.fn.init(a)}function g(a,c,b){if(!b.contentWindow.postMessage)return!1;a=JSON.stringify({method:a,value:c});b.contentWindow.postMessage(a,h)}function l(a){var c,b;try{c=JSON.parse(a.data),b=c.event||c.method}catch(e){}"ready"!=b||k||(k=!0);if(!/^https?:\/\/player.vimeo.com/.test(a.origin))return!1;"*"===h&&(h=a.origin);a=c.value;var m=c.data,f=""===f?null:c.player_id;c=f?d[f][b]:d[b];b=[];if(!c)return!1;void 0!==a&&b.push(a);m&&b.push(m);f&&b.push(f);
return 0<b.length?c.apply(null,b):c.call()}function n(a,c,b){b?(d[b]||(d[b]={}),d[b][a]=c):d[a]=c}var d={},k=!1,h="*";e.fn=e.prototype={element:null,init:function(a){"string"===typeof a&&(a=document.getElementById(a));this.element=a;return this},api:function(a,c){if(!this.element||!a)return!1;var b=this.element,d=""!==b.id?b.id:null,e=c&&c.constructor&&c.call&&c.apply?null:c,f=c&&c.constructor&&c.call&&c.apply?c:null;f&&n(a,f,d);g(a,e,b);return this},addEvent:function(a,c){if(!this.element)return!1;
var b=this.element,d=""!==b.id?b.id:null;n(a,c,d);"ready"!=a?g("addEventListener",a,b):"ready"==a&&k&&c.call(null,d);return this},removeEvent:function(a){if(!this.element)return!1;var c=this.element,b=""!==c.id?c.id:null;a:{if(b&&d[b]){if(!d[b][a]){b=!1;break a}d[b][a]=null}else{if(!d[a]){b=!1;break a}d[a]=null}b=!0}"ready"!=a&&b&&g("removeEventListener",a,c)}};e.fn.init.prototype=e.fn;window.addEventListener?window.addEventListener("message",l,!1):window.attachEvent("onmessage",l);return window.Froogaloop=
window.$f=e}();

/*
* FlowType.JS v1.1
* Copyright 2013-2014, Simple Focus http://simplefocus.com/
*
*/
!function(n){n.fn.flowtype=function(i){var m=n.extend({maximum:9999,minimum:1,maxFont:9999,minFont:8,fontRatio:33},i),t=function(i){var t=n(i),o=t.width(),u=o>m.maximum?m.maximum:o<m.minimum?m.minimum:o,a=u/m.fontRatio,f=a>m.maxFont?m.maxFont:a<m.minFont?m.minFont:a;t.css("font-size",f+"px")};return this.each(function(){var i=this;n(window).resize(function(){t(i)}),t(this)})}}(jQuery);

/**
 * @package		Mb2 Slider in Devices
 * @version		1.0.0
 * @author		Mariusz Boloz (http://mb2extensions.com)
 * @copyright	Copyright (C) 2016 Mariusz Boloz (http://mb2extensions.com). All rights reserved
 * @license		Commercial (http://codecanyon.net/licenses)
**/
jQuery(document).ready(function(e){e(".mb2sid").each(function(){function t(e,t,i,a,o,d,s,r,l){if(i>=l){var h=l*a,c=l*o,u=h*d,f=l*r,p=h*s;e.css({width:l,height:h}),t.css({width:c,height:u,left:f,top:p}),n.css({width:c,height:u})}else{var g=s*(a*i),m=r*i,v=i*a,c=i*o,u=i*a*d;e.css({width:i,height:v}),t.css({width:c,height:u,left:m,top:g}),n.css({width:c,height:u})}}var i=e(this),a=i.find("> .mb2sid-inner"),n=a.find(".mb2sid-slide-item"),o=i.data("width"),d=i.data("height"),s=i.data("swidth"),r=i.data("sheight"),l=i.data("sleft"),h=i.data("stop"),c=i.parent().width();t(i,a,o,d,s,r,h,l,c),e(window).resize(function(){var e=i.parent().width();t(i,a,o,d,s,r,h,l,e)})});var t=null;e(".mb2sid-slide-list").each(function(){function i(){if(t){console.log(t);var e=c.eq(t-1).find(".mb2sid-youtube").get(0),i=c.eq(t-1).find(".mb2sid-vimeo").get(0);console.log(i),e?e.contentWindow.postMessage('{"event":"command","func":"pauseVideo","args":""}',"*"):i&&$f(i).api("pause")}}var a=e(this),n=a.data("mode"),o=1==a.data("auto")?!0:!1,d=a.data("aspeed"),s=a.data("apause"),r=1==a.data("loop")?!0:!1,l=1==a.data("pager")?!0:!1,h=1==a.data("control")?!0:!1,c=a.find("> li"),u=1==a.data("vertical")?!0:!1,f=a.data("verh"),p=u?"mb2sid_icon-up-open":"mb2sid_icon-left-open",g=u?"mb2sid_icon-down-open":"mb2sid_icon-right-open";a.lightSlider({item:1,autoWidth:!1,slideMove:1,slideMargin:0,addClass:"",mode:n,useCSS:!0,cssEasing:"ease",easing:"linear",speed:d,auto:o,loop:r,slideEndAnimation:!0,pause:s,keyPress:!1,controls:h,prevHtml:'<span class="'+p+'"></span>',nextHtml:'<span class="'+g+'"></span>',rtl:!1,adaptiveHeight:!1,vertical:u,verticalHeight:f,vThumbWidth:100,thumbItem:10,pager:l,gallery:!1,galleryMargin:5,thumbMargin:5,currentPagerPosition:"middle",enableTouch:!0,enableDrag:!0,freeMove:!0,swipeThreshold:40,responsive:[],onBeforeStart:function(e){},onSliderLoad:function(e){t=a.getCurrentSlideCount()},onAfterSlide:function(e){t=a.getCurrentSlideCount()},onBeforeSlide:function(e){i()},onBeforeNextSlide:function(e){},onBeforePrevSlide:function(e){}})}),e(".mb2sid-caption").each(function(){var t=e(this),i=t.data("fratio");e(".mb2sid-caption").flowtype({fontRatio:i})})});